[workspace]
name = "alphagenome_modal"
version = "0.1.0"
description = "Alphagenome inference microservice and training pipeline using Modal"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = "~=3.12.0"
pytorch = "*"
pylance = ">=4.0.0,<5"
duckdb = ">=1.5.2,<2"
xz = ">=5.8.3,<6"


[pypi-dependencies]
modal = "*" # TODO: need to be more specific with the version
jax = {version = "*", extras = ["cuda12"]}
huggingface-hub = "*"
fastapi = "*"
pydantic = "*"
marimo = "*"
requests = "*"
alphagenome-pytorch = { path = "./alphagenome-pytorch", editable = true }
alphagenome-modal = { path = ".", editable = true }
pybigwig = "*"
pandas = "*"
tqdm = "*"
pyfaidx = "*"
zstandard = ">=0.25.0, <0.26"
polars = ">=1.40.0, <2"
lancedb = "*"
pyarrow = "*"
dna-parser = "*"

[tasks]
modal-run = "modal run -m alphagenome_modal.app"
modal-deploy = "modal deploy -m alphagenome_modal.app"
modal-shell = "modal shell -m alphagenome_modal.app"
test-download = "modal run -m alphagenome_modal.download_test"
setup-model = "modal run -m alphagenome_modal.model_setup"
convert-weights = "modal run -m alphagenome_modal.model_setup::convert_to_pytorch"
serve-temp = "modal serve -m alphagenome_modal.inference"
serve-deploy = "modal deploy -m alphagenome_modal.inference"
serve-torch-temp = "modal serve -m alphagenome_modal.inference_agtorch"
serve-torch-deploy = "modal deploy -m alphagenome_modal.inference_agtorch"
embed-lance-serve = "modal serve -m alphagenome_modal.embed_to_lance"
embed-lance-deploy = "modal deploy -m alphagenome_modal.embed_to_lance"
