[workspace]
name = "modal_alphagenome"
version = "0.1.0"
description = "Alphagenome inference microservice and training pipeline using Modal"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = "~=3.14.0"

[pypi-dependencies]
modal = "*" # TODO: need to be more specific with the version
jax = {version = "*", extras = ["cuda12"]}
huggingface-hub = "*"
fastapi = "*"
pydantic = "*"
marimo = "*"
requests = "*"

[tasks]
modal-run = "modal run -m modal_alphagenome.app"
modal-deploy = "modal deploy -m modal_alphagenome.app"
modal-shell = "modal shell -m modal_alphagenome.app"
test-download = "modal run -m modal_alphagenome.download_test"
setup-model = "modal run -m modal_alphagenome.model_setup"
serve-temp = "modal serve modal_alphagenome.inference"
serve-deploy = "modal deploy modal_alphagenome.inference"
